# Environment configuration for llm_grasp_01
# Each object can be a mesh
# All dimensions are in meters
# Transforms are in the world frame

# Box object
platform:
  type: box
  dimensions: [5.0, 5.0, 0.025]  # length, width, height
  pose:
    position: [0.0, 0.0, -0.013]  # x, y, z
    orientation: [0.0, 0.0, 0.0]  # roll, pitch, yaw
  color: [0.8, 0.8, 0.8]  # light gray
  alpha: 0.0
  collision_enabled: true

# Back wall
back_wall:
  type: box
  dimensions: [0.025, 5.0, 2.0]
  pose:
    position: [-0.6, 0.0, 1.0]
    orientation: [0.0, 0.0, 0.0]
  color: [0.8, 0.8, 0.8]  # light gray
  alpha: 0.0
  collision_enabled: true

# Ceiling
ceiling_wall:
  type: box
  dimensions: [4.0, 4.0, 0.025]
  pose:
    position: [1.0, 0.0, 2.0]
    orientation: [0.0, 0.0, 0.0]
  color: [0.8, 0.8, 0.8]  # light gray
  alpha: 0.0
  collision_enabled: true

# Conveyor mesh
conveyor:
  type: mesh
  mesh_path: "package://pick_cell/assets/conveyor.stl"
  pose:
    position: [1.5, -0.6, 0.0]
    orientation: [0.0, 0.0, 1.57]
  scale: [1.0, 1.0, 1.0]
  collision_enabled: true
  alpha: 1.0
  color: [0.0, 0.0, 0.0]  # black

# Shelving mesh
shelving:
  type: mesh
  mesh_path: "package://pick_cell/assets/shelving.stl"
  pose:
    position: [0.4, 0.72, 0.0]
    orientation: [1.57, 0.0, 1.57]
  scale: [1.0, 1.0, 1.0]
  collision_enabled: true
  alpha: 1.0
  color: [0.4, 0.2, 0.1]  # brown/black shade

# Tote mesh
tote:
  type: mesh
  mesh_path: "package://pick_cell/assets/tote.stl"
  pose:
    position: [0.77, -0.44, 0.38]
    orientation: [0.0, 0.0, 0.0]
  scale: [1.0, 1.0, 1.0]
  collision_enabled: true
  alpha: 1.0
  color: [0.5, 0.5, 0.5]  # shade of gray

# kiosk
kiosk:
  type: mesh
  mesh_path: "package://pick_cell/assets/kiosk.stl"
  pose:
    position: [2.0, 0.0, 0.0]
    orientation: [1.57, 0.0, 1.57]
  scale: [0.6, 0.6, 0.6]
  collision_enabled: false
  alpha: 1.0
  color: [0.15, 0.25, 0.45]  # medium navy blue

# human
human:
  type: mesh
  mesh_path: "package://pick_cell/assets/human.stl"
  pose:
    position: [2.6, 0.2, 0.0]
    orientation: [1.57, 0.0, -1.57]
  scale: [0.55, 0.55, 0.55]
  collision_enabled: false
  alpha: 1.0
  color: [0.85, 0.75, 0.65]  # warm beige/skin tone

tool:
  type: mesh
  mesh_path: "package://pick_cell/assets/point_suction.stl"
  pose:
    position: [0.0, 0.01, 0.11]
    orientation: [1.57, 0.0, 0.0]
  color: [0.239, 0.349, 0.671]
  alpha: 1.0
  scale: [1.0, 1.0, 1.0]
  collision_enabled: true
  tcp:
    pose:
      position: [0.0, 0.07, 0.0]
      orientation: [-1.57, 0.0, 0.0]

# Grasp configurations
grasps:
  # Grasp for tote center
  tote:
    poses:
      - position: [0.77, -0.44, 0.8]
        orientation: [-3.14, 0.0, 0.0]
  shelving:
    poses:
      - position: [0.8, 0.4, 0.2]
        orientation: [-1.57, 0, 0]
      - position: [0.8, 0.4, 0.6]
        orientation: [-1.57, 0, 0]
      - position: [0.8, 0.4, 1.0]
        orientation: [-1.57, 0, 0]
      - position: [0.8, 0.4, 1.4]
        orientation: [-1.57, 0, 0]
      - position: [0.8, 0.4, 1.8]
        orientation: [-1.57, 0, 0]
      - position: [1.3, 0.4, 0.2]
        orientation: [-1.57, 0, 0]
      - position: [1.3, 0.4, 0.6]
        orientation: [-1.57, 0, 0]
      - position: [1.3, 0.4, 1.0]
        orientation: [-1.57, 0, 0]
      - position: [1.3, 0.4, 1.4]
        orientation: [-1.57, 0, 0]
      - position: [1.3, 0.4, 1.8]
        orientation: [-1.57, 0, 0]