services:
  robot_learning:
    platform: linux/arm64
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: robot_learning
    privileged: true
    cap_add:
      - NET_ADMIN  # Allow network modifications inside container
    volumes:
      - ..:/robot_learning
    stdin_open: true
    tty: true
    environment:
      - ROS_MASTER_URI=http://192.168.0.31:11311
      - ROS_IP=192.168.0.31
      - DISPLAY=:1
      - QT_X11_NO_MITSHM=1
      - QT_QPA_PLATFORM=xcb
      - NO_VNC_PORT=8080
    network_mode: "host"