services:
  robot_learning:
    platform: linux/arm64
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: robot_learning
    privileged: true
    cap_add:
      - NET_ADMIN  # Allow network modifications inside container
    volumes:
      - ..:/robot_learning
    stdin_open: true
    tty: true
    environment:
      - ROS_MASTER_URI=http://192.168.0.31:11311
      - ROS_IP=192.168.0.31
      - DISPLAY=novnc:0.0
      - QT_X11_NO_MITSHM=1
      - QT_QPA_PLATFORM=xcb
    network_mode: "host"
    depends_on:
      - vnc
  vnc:
    image: dorowu/ubuntu-desktop-lxde-vnc:focal-arm64
    environment:
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1200
    ports:
      - "5901:5901"  # VNC server port
    networks:
      - x11

  novnc:
    image: theasp/novnc:latest
    environment:
      - VNC_HOST=vnc:5901
    ports:
      - "8080:8080"
    networks:
      - x11
    depends_on:
      - vnc

networks:
  x11: