# Environment configuration for MoveIt scene
# Each object can be a box, sphere, cylinder, or mesh
# All dimensions are in meters
# Colors are in RGB format (0-1)
# Transforms are in the world frame

objects:
  # Box object
  platform:
    type: box
    dimensions: [5.0, 5.0, 0.025]  # length, width, height
    pose:
      position: [0.0, 0.0, -0.013]  # x, y, z
      orientation: [0.0, 0.0, 0.0]  # roll, pitch, yaw
    color: [0.8, 0.8, 0.8]  # light gray
    alpha: 0.0
    collision_enabled: true
    visible: true
  
  # Back wall
  back_wall:
    type: box
    dimensions: [0.025, 5.0, 2.0]
    pose:
      position: [-0.6, 0.0, 1.0]
      orientation: [0.0, 0.0, 0.0]
    color: [0.8, 0.8, 0.8]  # light gray
    alpha: 0.0
    collision_enabled: true
    visible: true

  # Ceiling
  ceiling_wall:
    type: box
    dimensions: [4.0, 4.0, 0.025]
    pose:
      position: [1.0, 0.0, 2.0]
      orientation: [0.0, 0.0, 0.0]
    color: [0.8, 0.8, 0.8]  # light gray
    alpha: 0.0
    collision_enabled: true
    visible: true

  robot_roi:
    type: box
    dimensions: [0.8, 2.0, 0.4]
    pose:
      position: [1.0, 0.0, 1.0]
      orientation: [0.0, 0.0, 0.0]
    color: [0.0, 1.0, 0.0]
    alpha: 0.1
    collision_enabled: false
    visible: true
  
  perception_roi:
    type: box
    dimensions: [0.8, 2.0, 0.7]
    pose:
      position: [1.0, 0.0, 0.75]
      orientation: [0.0, 0.0, 0.0]
    color: [0.0, 1.0, 0.0]
    alpha: 0.0
    collision_enabled: false
    visible: true

  # Mesh object
  table_mesh:
    type: mesh
    mesh_path: "package://inspection_cell/assets/table.stl"
    pose:
      position: [1.0, 0.0, 0.6]
      orientation: [1.57, 0.0, 1.57]
    color: [0.588, 0.588, 0.557]
    alpha: 1.0
    scale: [1.0, 0.7, 1.0]
    collision_enabled: true
    visible: true
  
  part:
    # type: mesh
    # mesh_path: "package://inspection_cell/assets/jet_engine_casing.stl"
    # pose:
    #   position: [1.0, 0.0, 1.5]
    #   orientation: [0.0, -1.57, 0.0]
    # color: [0.922, 0.918, 0.88]
    # alpha: 1.0
    # scale: [2, 2, 2]
    # collision_enabled: true
    # visible: true

    # type: mesh
    # mesh_path: "package://inspection_cell/assets/engine_casing_1.stl"
    # pose:
    #   position: [0.8, -0.9, 0.4]
    #   orientation: [1.57, 0.0, 1.57]
    # color: [0.922, 0.918, 0.88]
    # alpha: 1.0
    # scale: [1.5, 1.5, 1.5]
    # collision_enabled: true
    # visible: true

    type: mesh
    mesh_path: "package://inspection_cell/assets/propeller.stl"
    pose:
      position: [0.8, 0.8, 0.65]
      orientation: [1.57, 0.0, 0.0]
    color: [0.922, 0.918, 0.88]
    alpha: 1.0
    scale: [0.7, 0.7, 0.7]
    collision_enabled: true
    visible: true

# Robot configuration
robot:
  group_name: "manipulator"
  planning_time: 2.0
  num_planning_attempts: 5
  max_velocity_scaling_factor: 1.0
  max_acceleration_scaling_factor: 1.0 