# Environment configuration for MoveIt scene
# Each object can be a box, sphere, cylinder, or mesh
# All dimensions are in meters
# Colors are in RGB format (0-1)
# Transforms are in the world frame

objects:
  # Box object
  table_box:
    type: box
    dimensions: [1.0, 0.8, 0.05]  # length, width, height
    pose:
      position: [0.5, 0.0, 0.025]  # x, y, z
      orientation: [0.0, 0.0, 0.0]  # roll, pitch, yaw
    color: [0.8, 0.8, 0.8]  # light gray
    alpha: 1.0
    collision_enabled: true
    visible: true

  # Sphere object
  ball:
    type: sphere
    radius: 0.1
    pose:
      position: [1.0, 0.0, 1.0]
      orientation: [0.0, 0.0, 0.0]
    color: [1.0, 0.0, 0.0]  # red
    alpha: 0.8
    collision_enabled: true
    visible: true

  # Cylinder object
  pillar:
    type: cylinder
    radius: 0.1
    height: 1.0
    pose:
      position: [0.0, 0.5, 0.5]
      orientation: [0.0, 0.0, 0.0]
    color: [0.0, 1.0, 0.0]  # green
    alpha: 0.7
    collision_enabled: true
    visible: true

  # Mesh object
  table_mesh:
    type: mesh
    mesh_path: "package://inspection_cell/assets/table.stl"
    pose:
      position: [0.0, 0.0, 0.0]
      orientation: [0.0, 0.0, 0.0]
    color: [0.588, 0.588, 0.557]
    alpha: 1.0
    collision_enabled: true
    visible: true

# Robot configuration
robot:
  group_name: "manipulator"
  planning_time: 2.0
  num_planning_attempts: 5
  max_velocity_scaling_factor: 1.0
  max_acceleration_scaling_factor: 1.0 