camera:
  # Camera frame configuration
  frame:
    reference_frame: "tool0"  # The frame the camera is mounted on
    transform:
      position: [0.0, 0.0, 0.1]  # Z axis is forward from tool0
      orientation: [0.0, 0.0, 0.0]  # Aligned with tool0 frame

  # Field of view configuration
  field_of_view:
    horizontal_fov: 60.0  # Horizontal field of view in degrees
    vertical_fov: 45.0    # Vertical field of view in degrees
    min_range: 0.1        # Minimum sensing range in meters
    max_range: 0.5        # Maximum sensing range in meters
  
  # Detection settings
  detection:
    target_object: "part"  # Only detect the part object
    intersection_quality: 20  # Number of points to sample for intersection test
    debug_mode: true       # Enable debug visualization

  # Sensing properties
  sensing:
    publish_rgb: true      # Whether to publish simulated RGB data
    publish_depth: true    # Whether to publish simulated depth data
    publish_point_cloud: true  # Whether to publish simulated point cloud
    noise_level: 0.01     # Standard deviation of noise to add to depth measurements in meters
    frame_rate: 30         # Simulated frame rate for publishing data

  # Visualization options
  visualization:
    show_camera_frame: true
    show_frustum: true
    show_intersection_points: true
    frustum_color: [0.0, 0.7, 1.0, 0.3]
    show_intersection: true 