# Perception configuration for simulated camera

# Mesh configuration
mesh:
  scene_object_name: "part"

# Camera configuration
camera:
  # Image size
  image_size: [480, 640]

  # Frame settings
  frame: "tool0"

  # Field of view settings
  field_of_view:
    horizontal_fov: 60.0
    vertical_fov: 45.0
    min_range: 0.1
    max_range: 0.8
    noise_level: 0.0
  
  # Sensing settings
  sensing:
    frame_rate: 30
    noise_level: 0.005
    publish_rgb: true
    publish_depth: true
    publish_point_cloud: true
  
  # Rendering settings
  rendering:
    shader_type: "soft_phong"
    
  # Visualization settings
  visualization:
    show_camera_frame: true
    show_frustum: true
    frustum_color: [0.0, 0.7, 1.0, 0.3]