# Perception configuration for simulated camera

# Mesh configuration
mesh:
  scene_object_name: "part"

# Camera configuration
camera:
  # Image size - minimal resolution for point cloud generation
  image_size: [120, 160]

  # Frame settings
  frame: "tool0"

  # Field of view settings
  field_of_view:
    horizontal_fov: 60.0
    vertical_fov: 45.0
    min_range: 0.1
    max_range: 0.8
  
  # Sensing settings
  sensing:
    frame_rate: 1  # Minimal frame rate for point cloud generation
    noise_level: 0.0
  
  # Rendering settings
  rendering:
    shader_type: "hard_phong"  # Using hard_phong for speed