# Mesh configuration
sensor:
  frame: "tcp"
  scene_xml: "package://neural_engine/config/inspection_sensor_scene.xml"

  intrinsics:
    width: 1024
    height: 1024
    fx: 886.81
    fy: 886.81
    cx: 512.0
    cy: 512.0

  floor:
    height: 0.0
    margin: 0.02

  constraints:
    depth:
      min: 0.2
      max: 0.8
    radius: 0.25
    orientation: 0.8

  dynamics:
    frame_rate: 10